# Generated by Django 3.0.2 on 2020-03-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BookRequestModel',
            fields=[
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Book_Title', models.CharField(max_length=200)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_ISBN', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Book Request',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book category', max_length=200)),
                ('icon', models.FileField(blank=True, upload_to='icons/', verbose_name='SVG File')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book publication', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200)),
                ('isbn', models.CharField(help_text='13 Character <a target="_blank" href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('published', models.DateField(help_text='Publication date', verbose_name='Published on')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Cover Image')),
                ('pdffile', models.FileField(blank=True, upload_to='files/', verbose_name='PDF File')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('book_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
            ],
            options={
                'ordering': ['posted_on'],
                'unique_together': {('email', 'book_linked')},
            },
        ),
    ]
